version: "3.7"
services:
  aerie_commanding:
    build:
      context: ./command-expansion-server
      dockerfile: Dockerfile
    container_name: aerie_commanding
    depends_on: ["postgres"]
    environment:
      LOG_FILE: console
      LOG_LEVEL: debug
      MERLIN_GRAPHQL_URL: http://hasura:8080/v1/graphql
      COMMANDING_SERVER_PORT: 27184
      COMMANDING_DB: aerie_commanding
      COMMANDING_DB_PASSWORD: "${AERIE_PASSWORD}"
      COMMANDING_DB_PORT: 5432
      COMMANDING_DB_SERVER: postgres
      COMMANDING_DB_USER: "${AERIE_USERNAME}"
      COMMANDING_LOCAL_STORE: /usr/src/app/commanding_file_store
    image: aerie_commanding
    ports: ["27184:27184"]
    restart: always
    volumes:
      - ./command-expansion-server:/app:cached
      - aerie_file_store:/usr/src/app/commanding_file_store
  aerie_gateway:
    container_name: aerie_gateway
    depends_on: ["postgres"]
    environment:
      AUTH_TYPE: none
      AUTH_URL: https://atb-ocio-12b.jpl.nasa.gov:8443/cam-api
      GQL_API_URL: http://localhost:8080/v1/graphql
      LOG_FILE: console
      LOG_LEVEL: debug
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      PORT: 9000
      POSTGRES_AERIE_MERLIN_DB: aerie_merlin
      POSTGRES_AERIE_SCHEDULER_DB: aerie_scheduler
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: "${AERIE_PASSWORD}"
      POSTGRES_PORT: 5432
      POSTGRES_USER: "${AERIE_USERNAME}"
    image: "ghcr.io/nasa-ammos/aerie-gateway:develop"
    ports: ["9000:9000"]
    restart: always
    volumes:
      - aerie_file_store:/app/files
  aerie_merlin:
    build:
      context: ./merlin-server
      dockerfile: Dockerfile
    container_name: aerie_merlin
    depends_on: ["postgres"]
    environment:
      MERLIN_DB: "aerie_merlin"
      MERLIN_DB_PASSWORD: "${AERIE_PASSWORD}"
      MERLIN_DB_PORT: 5432
      MERLIN_DB_SERVER: postgres
      MERLIN_DB_USER: "${AERIE_USERNAME}"
      MERLIN_LOCAL_STORE: /usr/src/app/merlin_file_store
      MERLIN_PORT: 27183
      JAVA_OPTS: >
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        -Dorg.slf4j.simpleLogger.defaultLogLevel=DEBUG
        -Dorg.slf4j.simpleLogger.log.com.zaxxer.hikari=INFO
        -Dorg.slf4j.simpleLogger.logFile=System.err
      UNTRUE_PLAN_START: "2000-01-01T11:58:55.816Z"
    image: aerie_merlin
    ports: ["27183:27183", "5005:5005"]
    restart: always
    volumes:
      - aerie_file_store:/usr/src/app/merlin_file_store
  aerie_scheduler:
    build:
      context: ./scheduler-server
      dockerfile: Dockerfile
    container_name: aerie_scheduler
    depends_on: ["aerie_merlin", "postgres"]
    environment:
      MERLIN_GRAPHQL_URL: http://hasura:8080/v1/graphql
      MERLIN_LOCAL_STORE: /usr/src/app/merlin_file_store
      SCHEDULER_DB: "aerie_scheduler"
      SCHEDULER_DB_PASSWORD: "${AERIE_PASSWORD}"
      SCHEDULER_DB_PORT: 5432
      SCHEDULER_DB_SERVER: postgres
      SCHEDULER_DB_USER: "${AERIE_USERNAME}"
      SCHEDULER_LOCAL_STORE: /usr/src/app/scheduler_file_store
      SCHEDULER_LOGGING: "true"
      SCHEDULER_OUTPUT_MODE: UpdateInputPlanWithNewActivities
      SCHEDULER_PORT: 27185
      SCHEDULER_RULES_JAR: /usr/src/app/merlin_file_store/scheduler_rules.jar
      JAVA_OPTS: >
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        -Dorg.slf4j.simpleLogger.defaultLogLevel=DEBUG
        -Dorg.slf4j.simpleLogger.log.com.zaxxer.hikari=INFO
        -Dorg.slf4j.simpleLogger.logFile=System.err
    image: aerie_scheduler
    ports: ["27185:27185", "5006:5005"]
    restart: always
    volumes:
      - aerie_file_store:/usr/src/app/merlin_file_store
  aerie_ui:
    container_name: aerie_ui
    depends_on: ["postgres"]
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      ORIGIN: http://localhost
      PUBLIC_AUTH_TYPE: none
      PUBLIC_GATEWAY_CLIENT_URL: http://localhost:9000
      PUBLIC_GATEWAY_SERVER_URL: http://aerie_gateway:9000
      PUBLIC_HASURA_CLIENT_URL: http://localhost:8080/v1/graphql
      PUBLIC_HASURA_SERVER_URL: http://hasura:8080/v1/graphql
      PUBLIC_HASURA_WEB_SOCKET_URL: ws://localhost:8080/v1/graphql
    image: "ghcr.io/nasa-ammos/aerie-ui:develop"
    ports: ["80:80"]
    restart: always
  aerie_merlin_worker_1:
    build:
      context: ./merlin-worker
      dockerfile: Dockerfile
    container_name: aerie_merlin_worker_1
    depends_on: ["postgres"]
    environment:
      MERLIN_WORKER_DB: "aerie_merlin"
      MERLIN_WORKER_DB_PASSWORD: "${AERIE_PASSWORD}"
      MERLIN_WORKER_DB_PORT: 5432
      MERLIN_WORKER_DB_SERVER: postgres
      MERLIN_WORKER_DB_USER: "${AERIE_USERNAME}"
      MERLIN_WORKER_LOCAL_STORE: /usr/src/app/merlin_file_store
      JAVA_OPTS: >
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        -Dorg.slf4j.simpleLogger.defaultLogLevel=DEBUG
        -Dorg.slf4j.simpleLogger.log.com.zaxxer.hikari=INFO
        -Dorg.slf4j.simpleLogger.logFile=System.err
      UNTRUE_PLAN_START: "2000-01-01T11:58:55.816Z"
    ports: ["5007:5005", "27187:8080"]
    restart: always
    volumes:
      - aerie_file_store:/usr/src/app/merlin_file_store:ro
  aerie_merlin_worker_2:
    build:
      context: ./merlin-worker
      dockerfile: Dockerfile
    container_name: aerie_merlin_worker_2
    depends_on: ["postgres"]
    environment:
      MERLIN_WORKER_DB: "aerie_merlin"
      MERLIN_WORKER_DB_PASSWORD: "${AERIE_PASSWORD}"
      MERLIN_WORKER_DB_PORT: 5432
      MERLIN_WORKER_DB_SERVER: postgres
      MERLIN_WORKER_DB_USER: "${AERIE_USERNAME}"
      MERLIN_WORKER_LOCAL_STORE: /usr/src/app/merlin_file_store
      JAVA_OPTS: >
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        -Dorg.slf4j.simpleLogger.defaultLogLevel=DEBUG
        -Dorg.slf4j.simpleLogger.log.com.zaxxer.hikari=INFO
        -Dorg.slf4j.simpleLogger.logFile=System.err
      UNTRUE_PLAN_START: "2000-01-01T11:58:55.816Z"
    ports: ["5008:5005", "27188:8080"]
    restart: always
    volumes:
      - aerie_file_store:/usr/src/app/merlin_file_store:ro
  hasura:
    container_name: hasura
    depends_on: ["postgres"]
    environment:
      AERIE_MERLIN_DATABASE_URL: "postgres://${AERIE_USERNAME}:${AERIE_PASSWORD}@postgres:5432/aerie_merlin"
      AERIE_SCHEDULER_DATABASE_URL: "postgres://${AERIE_USERNAME}:${AERIE_PASSWORD}@postgres:5432/aerie_scheduler"
      AERIE_COMMANDING_DATABASE_URL: "postgres://${AERIE_USERNAME}:${AERIE_PASSWORD}@postgres:5432/aerie_commanding"
      AERIE_UI_DATABASE_URL: "postgres://${AERIE_USERNAME}:${AERIE_PASSWORD}@postgres:5432/aerie_ui"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_LOG_LEVEL: info
      HASURA_GRAPHQL_METADATA_DATABASE_URL: "postgres://${AERIE_USERNAME}:${AERIE_PASSWORD}@postgres:5432/aerie_hasura"
      HASURA_GRAPHQL_METADATA_DIR: /hasura-metadata
    image: "hasura/graphql-engine:v2.8.4.cli-migrations-v3"
    ports: ["8080:8080"]
    restart: always
    volumes:
      - ./deployment/hasura/metadata:/hasura-metadata
  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      AERIE_USERNAME: "${AERIE_USERNAME}"
      AERIE_PASSWORD: "${AERIE_PASSWORD}"
    image: postgres:14.1
    ports: ["5432:5432"]
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./deployment/postgres-init-db:/docker-entrypoint-initdb.d

volumes:
  aerie_file_store:
  mission_file_store:
  postgres_data:
