version: "3.3"
services:
  adaptation:
    image: "${DOCKER_URL}/adaptation:${ADAPTATION_DOCKER_TAG}"
    ports: ["27182:27182"]
    depends_on: ["adaptation_mongo"]
    volumes:
      - adaptation_files:/usr/src/app/adaptation_files
  adaptation_mongo:
    command: ["mongod", "--port", "27020", "--smallfiles"]
    image: mongo:3.2
    ports: ["27020:27020"]
    volumes: ["adaptation_mongo_data:/data/db"]
  plan:
    image: "${DOCKER_URL}/plan:${PLAN_DOCKER_TAG}"
    depends_on: ["plan_mongo"]
    ports: ["27183:27183"]
    restart: always
  plan_mongo:
    command: ["mongod", "--port", "27018", "--smallfiles"]
    image: mongo:3.2
    ports: ["27018:27018"]
    volumes: ["plan_mongo_data:/data/db"]

volumes:
  adaptation_files:
  adaptation_mongo_data:
  plan_mongo_data:
