apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: aerie-dev
  name: aerie-sequencing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aerie-sequencing
  template:
    metadata:
      labels:
        app: aerie-sequencing
    spec:
      containers:
        - name: aerie-sequencing
          image: ghcr.io/nasa-ammos/aerie-sequencing:develop
          ports:
            - containerPort: 27184
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/app/sequencing_file_store
              name: aerie-file-store
          env:
            - name: LOG_FILE
              value: console
            - name: LOG_LEVEL
              value: warn
            - name: MERLIN_GRAPHQL_URL
              value: http://hasura:8080/v1/graphql
            - name: SEQUENCING_DB
              value: aerie_sequencing
            - name: SEQUENCING_DB_PORT
              value: "5432"
            - name: SEQUENCING_DB_SERVER
              value: postgres
            - name: SEQUENCING_LOCAL_STORE
              value: /usr/src/app/sequencing_file_store
            - name: SEQUENCING_SERVER_PORT
              value: "27184"
            - name: SEQUENCING_DB_USER
              valueFrom:
                secretKeyRef:
                  name: dev-env
                  key: AERIE_USERNAME
            - name: SEQUENCING_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-env
                  key: AERIE_PASSWORD
      restartPolicy: Always
      volumes:
        - name: aerie-file-store
          persistentVolumeClaim:
            claimName: aerie-file-store
