apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: aerie-dev
  name: aerie-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aerie-scheduler
  template:
    metadata:
      labels:
        app: aerie-scheduler
    spec:
      containers:
        - name: aerie-scheduler
          image: ghcr.io/nasa-ammos/aerie-scheduler:develop
          ports:
            - containerPort: 27185
          volumeMounts:
            - mountPath: /usr/src/app/merlin_file_store
              name: aerie-file-store
          env:
            - name: JAVA_OPTS
              value: |
                -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -Dorg.slf4j.simpleLogger.logFile=System.err
            - name: MERLIN_GRAPHQL_URL
              value: http://hasura:8080/v1/graphql
            - name: SCHEDULER_DB
              value: aerie_scheduler
            - name: SCHEDULER_DB_PORT
              value: "5432"
            - name: SCHEDULER_DB_SERVER
              value: postgres
            - name: SCHEDULER_PORT
              value: "27185"
            - name: SCHEDULER_DB_USER
              valueFrom:
                secretKeyRef:
                  name: dev-env
                  key: AERIE_USERNAME
            - name: SCHEDULER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-env
                  key: AERIE_PASSWORD
      restartPolicy: Always
      volumes:
        - name: aerie-file-store
          persistentVolumeClaim:
            claimName: aerie-file-store
